# Generated by Django 4.2.1 on 2023-07-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_default_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_country',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_county',
            field=models.CharField(blank=True, choices=[('Avon', 'Avon'), ('Bedfordshire', 'Bedfordshire'), ('Berkshire', 'Berkshire'), ('Cambridgeshire', 'Cambridgeshire'), ('Buckinghamshire', 'Buckinghamshire'), ('Cheshire', 'Cheshire'), ('Cornwall', 'Cornwall'), ('Cumbria', 'Cumbria'), ('Derbyshire', 'Derbyshire'), ('Devon', 'Devon'), ('Dorset', 'Dorset'), ('Durham', 'Durham'), ('Essex', 'Essex'), ('Gloucestershire', 'Gloucestershire'), ('Hampshire', 'Hampshire'), ('Herefordshire', 'Herefordshire'), ('Hertfordshire', 'Hertfordshire'), ('Kent', 'Kent'), ('Lancashire', 'Lancashire')], max_length=80, null=True),
        ),
    ]
