# Generated by Django 4.2.1 on 2023-07-14 22:59

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_original_basket_order_stripe_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='county',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
