# Generated by Django 4.2.1 on 2023-07-20 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='entry',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='EntryType',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
