# Generated by Django 4.2.1 on 2023-07-20 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0002_remove_response_entry_delete_entry_delete_entrytype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('postreview_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='type', to='reviews.entrytype')),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('postreview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='reviews.postreview')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
