# Generated by Django 4.2.1 on 2023-07-21 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_is_meat_free'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_review', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='postreview',
            name='postreview_type',
        ),
        migrations.RemoveField(
            model_name='reviewresponse',
            name='postreview',
        ),
        migrations.DeleteModel(
            name='EntryType',
        ),
        migrations.DeleteModel(
            name='PostReview',
        ),
        migrations.DeleteModel(
            name='ReviewResponse',
        ),
    ]
