# Generated by Django 4.2.1 on 2023-07-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_remove_entry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='excerpt',
        ),
        migrations.AlterField(
            model_name='response',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
