# Generated by Django 4.2.1 on 2023-07-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_meat_free',
        ),
    ]
